name: Every 10 Minutes schedule

on:
  schedule:
    - cron: '*/10 * * * *' 

jobs:
  ten_minutes_schedule_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display current time
        run: |
          echo "Current Time"
          echo "UTC   : $(date +"%Y-%m-%dT%H:%M:%SZ")"
          echo "SEOUL : $(TZ=Asia/Seoul date +"%Y-%m-%dT%H:%M:%SZ")"
